FE_BASE_URL: ${FE_URL_ENV}

application:
  security:
    jwt:
      #secret-key:
      secret-key: ${JWT_SECRET_KEY}
      # a day 86,400,000 milliseconds (86,400,000ms÷1000=86,400s / 86,400s÷60=1,440min)
      # 1,440min÷60=24hours / 24hours÷24=1day tương tự cho cái hết hạn
      expiration: 86400000
      refresh-token:
        expiration: 2592000000 # 30 days

#----------------------------------------------------------------

# Kết nối user với quyền bucket cho máy chủ local
aws:
  region: ap-northeast-1
  s3:
    buckets:
      product: next-app-ecommerce
      #user: next-app-ecommerce
      category-bucket: category-bucket-ecommerce
  credentials:
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_KEY}
#----------------------------------------------------------------
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql-ecommerce-database:3306/ecommerce-test-db
    username: root
    password: thuong191020
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        #spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      # option :  none / validate / create / create-drop / update
      # if not config this jpa.hibernate the default is : create-drop
      ddl-auto: validate
    # show log database for debug
    show-sql: true
    #----------------------------------------------------------------
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - email
              - profile
  #            github:
  #              client-id: YOUR_GITHUB_CLIENT_ID
  #              client-secret: YOUR_GITHUB_CLIENT_SECRET
  #              redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  #              scope:
  #                - read:user
  # Cấu hình file tải lên của MultipartFile
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

